### ISSUE TITLE
Roadmap to Beta

### ISSUE THREAD

**Issue by jiftechnify** [jiftechnify/nosaray#2]
- [ ] Additional methods to select time range
  - Specifying absolute time for both `since` and `until`
  - Last `N` minutes / hours / days (until now)
- [ ] Additional targets
  - Posts of myself and/or specific user(s)
  - Posts on relays in specific "relay set" e.g. relays for Japanese posts
    - It should be usable without login
  - Long-form contents? public chat?
- [ ] Save a list of posts as a [categorized bookmark list](https://github.com/nostr-protocol/nips/blob/master/51.md#categorized-bookmarks-list) (kind 30001)
  - This enables *nostric* approach of integration other Nostr apps like [Nosli](https://nosli.vercel.app/)
- [ ] Resolve links in contents
  - In-Nostr links: Replies, Reposts, Quote Reposts
  - External links
  - Media (Images, Videos, etc)
  - Embeds?

**Comment by jiftechnify** [comment]
-[ ] Responsive UI
